#!/usr/bin/env bash
# =============================================================================
# WEHTTAMSNAPS - Widget Generator Script
# =============================================================================
# Generates custom widgets for Quickshell/Noctalia-Shell integration
# Creates branded components with Catppuccin Mocha theme
# =============================================================================

# Configuration
CONFIG_DIR="$HOME/.config/wehttamsnaps/widgets"
OUTPUT_DIR="$HOME/.config/quickshell/widgets"

# Catppuccin Mocha Colors
ROSEWATER="#f5e0dc"
FLAMINGO="#f2cdcd"
PINK="#f5c2e7"
MAUVE="#cba6f7"
RED="#f38ba8"
MAROON="#eba0ac"
PEACH="#fab387"
YELLOW="#f9e2af"
GREEN="#a6e3a1"
TEAL="#94e2d5"
SKY="#89dceb"
SAPPHIRE="#74c7ec"
BLUE="#89b4fa"
LAVENDER="#b4befe"
TEXT="#cdd6f4"
SUBTEXT1="#bac2de"
SUBTEXT2="#a6adc8"
OVERLAY2="#9399b2"
OVERLAY1="#7f849c"
OVERLAY0="#6c7086"
SURFACE2="#585b70"
SURFACE1="#45475a"
SURFACE0="#313244"
BASE="#1e1e2e"
MANTLE="#181825"
CRUST="#11111b"

# Color codes for terminal
RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
PURPLE='\033[0;35m'
NC='\033[0m'

# =============================================================================
# Functions
# =============================================================================

log() {
    echo -e "${CYAN}[WidgetGen]${NC} $1"
}

error() {
    echo -e "${RED}[WidgetGen ERROR]${NC} $1"
}

success() {
    echo -e "${GREEN}[WidgetGen]${NC} $1"
}

# Generate a clock widget
generate_clock_widget() {
    local name="${1:-wehttamsnaps-clock}"
    local style="${2:-digital}"  # digital, analog, minimal
    
    log "Generating clock widget: $name (style: $style)"
    
    mkdir -p "$OUTPUT_DIR"
    
    cat > "$OUTPUT_DIR/$name.qml" << EOF
// WehttamSnaps Clock Widget
// Generated by widget-generator.sh
// Style: $style

import QtQuick
import QtQuick.Layouts
import Quickshell
import Quickshell.Widgets

Rectangle {
    id: root
    implicitWidth: 200
    implicitHeight: 60
    color: "$BASE"
    radius: 12
    
    // Gradient border effect
    Rectangle {
        anchors.fill: parent
        anchors.margins: 2
        radius: 10
        color: "transparent"
        border.width: 2
        border.color: Qt.binding(() => {
            // Animated gradient border
            let t = Date.now() / 2000
            let r = Math.sin(t) * 0.5 + 0.5
            return Qt.rgba(
                0x89/255 * (1-r) + 0xcb/255 * r,  // Blue to Purple
                0xb4/255 * (1-r) + 0xa6/255 * r,
                0xfa/255 * (1-r) + 0xf7/255 * r,
                1.0
            )
        })
    }
    
    RowLayout {
        anchors.centerIn: parent
        spacing: 10
        
        // Time display
        Text {
            id: timeText
            font.family: "JetBrains Mono"
            font.pixelSize: 24
            font.bold: true
            color: "$TEXT"
            text: Qt.formatDateTime(new Date(), "hh:mm")
        }
        
        // Separator
        Rectangle {
            width: 2
            height: 30
            color: "$MAUVE"
            radius: 1
        }
        
        // Date display
        Text {
            id: dateText
            font.family: "JetBrains Mono"
            font.pixelSize: 12
            color: "$SUBTEXT1"
            text: Qt.formatDateTime(new Date(), "ddd MMM dd")
        }
    }
    
    // Update time every second
    Timer {
        interval: 1000
        running: true
        repeat: true
        onTriggered: {
            timeText.text = Qt.formatDateTime(new Date(), "hh:mm")
            dateText.text = Qt.formatDateTime(new Date(), "ddd MMM dd")
        }
    }
}
EOF
    
    success "Created clock widget: $OUTPUT_DIR/$name.qml"
}

# Generate a system stats widget
generate_stats_widget() {
    local name="${1:-wehttamsnaps-stats}"
    
    log "Generating system stats widget: $name"
    
    mkdir -p "$OUTPUT_DIR"
    
    cat > "$OUTPUT_DIR/$name.qml" << EOF
// WehttamSnaps System Stats Widget
// Shows CPU, RAM, GPU usage with Catppuccin styling

import QtQuick
import QtQuick.Layouts
import Quickshell
import Quickshell.Widgets

Rectangle {
    id: root
    implicitWidth: 300
    implicitHeight: 100
    color: "$BASE"
    radius: 12
    
    // Gradient border
    Rectangle {
        anchors.fill: parent
        anchors.margins: 2
        radius: 10
        color: "transparent"
        border.width: 2
        border.color: "$MAUVE"
    }
    
    ColumnLayout {
        anchors.fill: parent
        anchors.margins: 15
        spacing: 8
        
        // CPU Usage
        RowLayout {
            Layout.fillWidth: true
            spacing: 10
            
            Text {
                text: "CPU"
                font.family: "JetBrains Mono"
                font.pixelSize: 12
                color: "$BLUE"
                Layout.preferredWidth: 40
            }
            
            Rectangle {
                Layout.fillWidth: true
                height: 8
                radius: 4
                color: "$SURFACE0"
                
                Rectangle {
                    id: cpuBar
                    width: parent.width * 0.4  // Placeholder
                    height: parent.height
                    radius: 4
                    color: "$BLUE"
                }
            }
            
            Text {
                id: cpuPercent
                text: "40%"
                font.family: "JetBrains Mono"
                font.pixelSize: 12
                color: "$TEXT"
                Layout.preferredWidth: 40
            }
        }
        
        // RAM Usage
        RowLayout {
            Layout.fillWidth: true
            spacing: 10
            
            Text {
                text: "RAM"
                font.family: "JetBrains Mono"
                font.pixelSize: 12
                color: "$GREEN"
                Layout.preferredWidth: 40
            }
            
            Rectangle {
                Layout.fillWidth: true
                height: 8
                radius: 4
                color: "$SURFACE0"
                
                Rectangle {
                    id: ramBar
                    width: parent.width * 0.6  // Placeholder
                    height: parent.height
                    radius: 4
                    color: "$GREEN"
                }
            }
            
            Text {
                id: ramPercent
                text: "60%"
                font.family: "JetBrains Mono"
                font.pixelSize: 12
                color: "$TEXT"
                Layout.preferredWidth: 40
            }
        }
        
        // GPU Usage (AMD)
        RowLayout {
            Layout.fillWidth: true
            spacing: 10
            
            Text {
                text: "GPU"
                font.family: "JetBrains Mono"
                font.pixelSize: 12
                color: "$RED"
                Layout.preferredWidth: 40
            }
            
            Rectangle {
                Layout.fillWidth: true
                height: 8
                radius: 4
                color: "$SURFACE0"
                
                Rectangle {
                    id: gpuBar
                    width: parent.width * 0.2  // Placeholder
                    height: parent.height
                    radius: 4
                    color: "$RED"
                }
            }
            
            Text {
                id: gpuPercent
                text: "20%"
                font.family: "JetBrains Mono"
                font.pixelSize: 12
                color: "$TEXT"
                Layout.preferredWidth: 40
            }
        }
    }
}
EOF
    
    success "Created stats widget: $OUTPUT_DIR/$name.qml"
}

# Generate a workspace indicator widget
generate_workspace_widget() {
    local name="${1:-wehttamsnaps-workspaces}"
    
    log "Generating workspace widget: $name"
    
    mkdir -p "$OUTPUT_DIR"
    
    cat > "$OUTPUT_DIR/$name.qml" << EOF
// WehttamSnaps Workspace Indicator Widget
// Shows active workspace with Catppuccin styling

import QtQuick
import QtQuick.Layouts
import Quickshell
import Quickshell.Wayland

Rectangle {
    id: root
    implicitWidth: 400
    implicitHeight: 40
    color: "$BASE"
    radius: 12
    
    // Gradient border
    Rectangle {
        anchors.fill: parent
        anchors.margins: 2
        radius: 10
        color: "transparent"
        border.width: 2
        border.color: "$SAPPHIRE"
    }
    
    RowLayout {
        anchors.centerIn: parent
        spacing: 8
        
        Repeater {
            model: [
                { name: "Browser", icon: "🌐", color: "$BLUE" },
                { name: "Term", icon: "💻", color: "$GREEN" },
                { name: "Game", icon: "🎮", color: "$RED" },
                { name: "Stream", icon: "📺", color: "$PURPLE" },
                { name: "Photo", icon: "📷", color: "$PEACH" },
                { name: "Media", icon: "🎬", color: "$YELLOW" },
                { name: "Chat", icon: "💬", color: "$TEAL" },
                { name: "Music", icon: "🎵", color: "$PINK" },
                { name: "Files", icon: "📁", color: "$MAROON" },
                { name: "Misc", icon: "⭐", color: "$LAVENDER" }
            ]
            
            delegate: Rectangle {
                Layout.preferredWidth: 32
                Layout.preferredHeight: 28
                radius: 8
                color: index === 0 ? modelData.color : "$SURFACE0"
                
                Text {
                    anchors.centerIn: parent
                    text: modelData.icon
                    font.pixelSize: 14
                }
                
                MouseArea {
                    anchors.fill: parent
                    hoverEnabled: true
                    cursorShape: Qt.PointingHandCursor
                    
                    ToolTip.visible: containsMouse
                    ToolTip.text: modelData.name
                    ToolTip.delay: 500
                    
                    onClicked: {
                        // Switch to workspace
                        console.log("Switch to workspace " + (index + 1))
                    }
                }
            }
        }
    }
}
EOF
    
    success "Created workspace widget: $OUTPUT_DIR/$name.qml"
}

# Generate a media player widget
generate_media_widget() {
    local name="${1:-wehttamsnaps-media}"
    
    log "Generating media player widget: $name"
    
    mkdir -p "$OUTPUT_DIR"
    
    cat > "$OUTPUT_DIR/$name.qml" << EOF
// WehttamSnaps Media Player Widget
// Shows current track with controls

import QtQuick
import QtQuick.Layouts
import Quickshell
import Quickshell.Widgets

Rectangle {
    id: root
    implicitWidth: 350
    implicitHeight: 70
    color: "$BASE"
    radius: 12
    
    // Gradient border
    Rectangle {
        anchors.fill: parent
        anchors.margins: 2
        radius: 10
        color: "transparent"
        border.width: 2
        border.color: "$PINK"
    }
    
    RowLayout {
        anchors.fill: parent
        anchors.margins: 15
        spacing: 15
        
        // Album art placeholder
        Rectangle {
            Layout.preferredWidth: 50
            Layout.preferredHeight: 50
            radius: 8
            color: "$SURFACE1"
            
            Text {
                anchors.centerIn: parent
                text: "🎵"
                font.pixelSize: 24
            }
        }
        
        // Track info and controls
        ColumnLayout {
            Layout.fillWidth: true
            spacing: 4
            
            Text {
                id: trackTitle
                text: "Not Playing"
                font.family: "JetBrains Mono"
                font.pixelSize: 14
                font.bold: true
                color: "$TEXT"
                elide: Text.ElideRight
                Layout.fillWidth: true
            }
            
            Text {
                id: trackArtist
                text: "Select a track"
                font.family: "JetBrains Mono"
                font.pixelSize: 11
                color: "$SUBTEXT1"
                elide: Text.ElideRight
                Layout.fillWidth: true
            }
            
            // Progress bar
            Rectangle {
                Layout.fillWidth: true
                height: 4
                radius: 2
                color: "$SURFACE0"
                
                Rectangle {
                    width: parent.width * 0.3
                    height: parent.height
                    radius: 2
                    color: "$PINK"
                }
            }
        }
        
        // Control buttons
        RowLayout {
            spacing: 8
            
            Text {
                text: "⏮"
                font.pixelSize: 16
                color: "$SUBTEXT1"
                
                MouseArea {
                    anchors.fill: parent
                    cursorShape: Qt.PointingHandCursor
                    onClicked: console.log("Previous")
                }
            }
            
            Text {
                text: "▶"
                font.pixelSize: 20
                color: "$TEXT"
                
                MouseArea {
                    anchors.fill: parent
                    cursorShape: Qt.PointingHandCursor
                    onClicked: console.log("Play/Pause")
                }
            }
            
            Text {
                text: "⏭"
                font.pixelSize: 16
                color: "$SUBTEXT1"
                
                MouseArea {
                    anchors.fill: parent
                    cursorShape: Qt.PointingHandCursor
                    onClicked: console.log("Next")
                }
            }
        }
    }
}
EOF
    
    success "Created media widget: $OUTPUT_DIR/$name.qml"
}

# Generate a branding banner widget
generate_banner_widget() {
    local name="${1:-wehttamsnaps-banner}"
    
    log "Generating branding banner widget: $name"
    
    mkdir -p "$OUTPUT_DIR"
    
    cat > "$OUTPUT_DIR/$name.qml" << EOF
// WehttamSnaps Branding Banner Widget
// Shows brand name with animated gradient

import QtQuick
import QtQuick.Layouts

Rectangle {
    id: root
    implicitWidth: 250
    implicitHeight: 50
    color: "transparent"
    
    RowLayout {
        anchors.centerIn: parent
        spacing: 10
        
        // Camera icon
        Text {
            text: "📷"
            font.pixelSize: 24
        }
        
        // Brand name with gradient
        Text {
            text: "WehttamSnaps"
            font.family: "JetBrains Mono"
            font.pixelSize: 20
            font.bold: true
            
            // Animated color
            color: Qt.binding(() => {
                let t = Date.now() / 3000
                let i = (Math.sin(t) + 1) / 2
                return Qt.rgba(
                    0x89/255 * (1-i) + 0xcb/255 * i,
                    0xb4/255 * (1-i) + 0xa6/255 * i,
                    0xfa/255 * (1-i) + 0xf7/255 * i,
                    1.0
                )
            })
        }
        
        // Tagline
        Text {
            text: "| Photography & Gaming"
            font.family: "JetBrains Mono"
            font.pixelSize: 11
            color: "#a6adc8"
        }
    }
    
    // Animation timer
    Timer {
        interval: 50
        running: true
        repeat: true
        onTriggered: root.update()
    }
}
EOF
    
    success "Created banner widget: $OUTPUT_DIR/$name.qml"
}

# Generate all widgets
generate_all() {
    log "Generating all widgets..."
    
    generate_clock_widget
    generate_stats_widget
    generate_workspace_widget
    generate_media_widget
    generate_banner_widget
    
    success "All widgets generated in $OUTPUT_DIR"
}

# List available widget templates
list_templates() {
    echo "Available Widget Templates:"
    echo ""
    echo "  clock     - Digital clock with date display"
    echo "  stats     - System stats (CPU/RAM/GPU)"
    echo "  workspace - Workspace indicator bar"
    echo "  media     - Media player controls"
    echo "  banner    - WehttamSnaps branding banner"
    echo "  all       - Generate all widgets"
}

# =============================================================================
# Main
# =============================================================================

mkdir -p "$CONFIG_DIR"
mkdir -p "$OUTPUT_DIR"

case "${1:-help}" in
    clock)
        generate_clock_widget "$2" "$3"
        ;;
    stats)
        generate_stats_widget "$2"
        ;;
    workspace)
        generate_workspace_widget "$2"
        ;;
    media)
        generate_media_widget "$2"
        ;;
    banner)
        generate_banner_widget "$2"
        ;;
    all)
        generate_all
        ;;
    list)
        list_templates
        ;;
    help|--help|-h)
        echo "WehttamSnaps Widget Generator"
        echo ""
        echo "Usage: $0 <widget-type> [name] [options]"
        echo ""
        list_templates
        echo ""
        echo "Examples:"
        echo "  $0 clock                # Generate clock widget"
        echo "  $0 stats my-stats       # Generate stats widget with custom name"
        echo "  $0 all                  # Generate all widgets"
        ;;
    *)
        error "Unknown widget type: $1"
        echo "Use: $0 list"
        exit 1
        ;;
esac